Added strokeArc to draw arcs and setCircle to draw cricles
diku-dk/diku-canvas pull request #19
Opened 2022-11-01 01:35 UTC by joshniemela

I've written some functions for drawing circles using the midpoint circle algorithm, I will continue with the ellipses if merged.

2022-11-01 08:21 UTC, kfl commented
Thanks for the PR 🚀 

You have changed the API compared to the one given in issue #17, you have changed angles to be given as `float` instead of `int`. What is the motivation for that? (I know why I suggested the API from #17, and would like to hear any counterarguments that I might not have considered).

2022-11-01 08:29 UTC, kfl requested changes

2022-11-01 08:29 UTC, kfl commented on canvas.fsi
> +val circlePoints: int -> (int*int) list
`circlePoints` should not be part on the interface.

2022-11-01 08:29 UTC, kfl commented on canvas.fsi
> +val strokeArc   : canvas -> color -> int * int -> int -> float -> float -> unit
There should probably be both a `strokeArc` and a `fillArc` function. It would be great if you could add that, you seem to have all the building blocks for it.

2022-11-01 09:58 UTC, joshniemela commented on canvas.fsi
> +val circlePoints: int -> (int*int) list
> Thanks for the PR rocket
> 
> You have changed the API compared to the one given in issue #17, you have changed angles to be given as `float` instead of `int`. What is the motivation for that? (I know why I suggested the API from #17, and would like to hear any counterarguments that I might not have considered).

My reasoning was since you mentioned it had to be in radians, I thought there would be too big of a loss in precision, alternatively it could work with degrees instead.

2022-11-01 14:02 UTC, kfl commented on canvas.fsi
> +val circlePoints: int -> (int*int) list
I think this is a reply to my general comment about the API and not my code review about the `circlePoint` in the interface?

It would be great to have you comment as a general comment, rather than a comment to the code review.

2022-11-01 15:59 UTC, joshniemela commented on canvas.fsi
> +val circlePoints: int -> (int*int) list
You mean I should put this comment under the API issue as well, or just as a reminder for next time?

2022-11-01 22:15 UTC, joshniemela commented
(I'm assuming what I'm writing here is a general comment?) 
Personally I think it would make more sense to have all drawing functions related to curves be in radians since that's what we tend to work with in maths etc regarding circles, another change that I'd like your opinion on is if I could change the drawing functions to go counterclockwise due to the same argument regarding standards in maths?

2023-09-06 10:21 UTC, kfl commented
Thank for the contribution.

This PR is no longer relevant for Canvas 2.0 because the internals have been completely reworked.

2023-09-06 10:21 UTC, closed without merging